{
  "formatVersion": "1.1",
  "component": {
    "group": "net.minecraftforge",
    "module": "eventbus",
    "version": "6.2.33",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.jodah",
          "module": "typetools",
          "version": {
            "requires": "0.6.3"
          }
        }
      ],
      "files": [
        {
          "name": "eventbus-6.2.33.jar",
          "url": "eventbus-6.2.33.jar",
          "size": 64014,
          "sha512": "d909de0dd528e07fda6c4068e3c1f680584aba3adbf0a2f7c5d6059857923feca96f2c24af0482c23988c4bdb577917c86da118ee7452870ed035a53de9b3542",
          "sha256": "c9c9aab0979e08a0489fc497ba433276648d5192608e53535bad881dfe14d712",
          "sha1": "3fae69cfa9c5095bcc25c0a8a3ed9b26c156f922",
          "md5": "0b419ea48f46de30ee4e6241e4fdf9d4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "net.jodah",
          "module": "typetools",
          "version": {
            "requires": "0.6.3"
          }
        }
      ],
      "files": [
        {
          "name": "eventbus-6.2.33.jar",
          "url": "eventbus-6.2.33.jar",
          "size": 64014,
          "sha512": "d909de0dd528e07fda6c4068e3c1f680584aba3adbf0a2f7c5d6059857923feca96f2c24af0482c23988c4bdb577917c86da118ee7452870ed035a53de9b3542",
          "sha256": "c9c9aab0979e08a0489fc497ba433276648d5192608e53535bad881dfe14d712",
          "sha1": "3fae69cfa9c5095bcc25c0a8a3ed9b26c156f922",
          "md5": "0b419ea48f46de30ee4e6241e4fdf9d4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "eventbus-6.2.33-sources.jar",
          "url": "eventbus-6.2.33-sources.jar",
          "size": 38730,
          "sha512": "d05ed9909ae7ba95599cb1c2ac2c2f5832c8888a34350da457abfd0148d74680799764819606973ccdc5f956bc25b4289af37cfbbd4f8f88b21fea5f69c40340",
          "sha256": "6973f199d644a1ba81d8f703c8599ddff07448f2f62c5c0c664d765c3ead16a6",
          "sha1": "296aff9f6e6298e17e19ace4bd8b02c45d823530",
          "md5": "3a556d48d4be9092b50bac648a926d2f"
        }
      ]
    }
  ]
}
