@rem Generated by fabricpy
@echo off
if defined JAVA_HOME (
  "%JAVA_HOME%\bin\java.exe" -jar "%~dp0gradle\wrapper\gradle-wrapper.jar" %*
) else (
  java -jar "%~dp0gradle\wrapper\gradle-wrapper.jar" %*
)
