modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="playtime"
version="1.1"
displayName="Playtime"
description="Poppy playtime"

[[dependencies.playtime]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.playtime]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"

